[0.011s] Invoking command in '/home/clue/jointer_ws/build/pi_pca9685_interfaces': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake /home/clue/jointer_ws/src/pi_pca9685_interfaces -DCMAKE_INSTALL_PREFIX=/home/clue/jointer_ws/install/pi_pca9685_interfaces
[0.023s] -- Found ament_cmake: 1.3.9 (/opt/ros/humble/share/ament_cmake/cmake)
[0.154s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.156s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.159s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.192s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.397s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.397s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[0.397s]   pi_pca9685_interfaces --arguments-file
[0.397s]   /home/clue/jointer_ws/build/pi_pca9685_interfaces/rosidl_adapter__arguments__pi_pca9685_interfaces.json
[0.397s]   --output-dir
[0.397s]   /home/clue/jointer_ws/build/pi_pca9685_interfaces/rosidl_adapter/pi_pca9685_interfaces
[0.397s]   --output-file
[0.397s]   /home/clue/jointer_ws/build/pi_pca9685_interfaces/rosidl_adapter/pi_pca9685_interfaces.idls)
[0.397s]   returned error code 1:
[0.398s] 
[0.398s]   Traceback (most recent call last):
[0.398s] 
[0.398s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.398s]       return _run_code(code, main_globals, None,
[0.398s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.398s]       exec(code, run_globals)
[0.398s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.398s]       sys.exit(main())
[0.398s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.398s]       abs_idl_file = convert_to_idl(
[0.398s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 29, in convert_to_idl
[0.398s]       return convert_action_to_idl(
[0.398s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/action/__init__.py", line 28, in convert_action_to_idl
[0.398s]       action = parse_action_string(package_name, input_file.stem, content)
[0.399s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 902, in parse_action_string
[0.399s]       goal_message = parse_message_string(
[0.399s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 544, in parse_message_string
[0.399s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[0.399s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 388, in __init__
[0.399s]       self.base_type = BaseType(
[0.399s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[0.399s]       raise InvalidResourceName(
[0.399s] 
[0.399s]   rosidl_adapter.parser.InvalidResourceName: 'pca9685_Goal' is an invalid
[0.399s]   message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[0.399s] 
[0.399s] Call Stack (most recent call first):
[0.399s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.400s]   CMakeLists.txt:16 (rosidl_generate_interfaces)
[0.400s] 
[0.400s] [0m
[0.400s] -- Configuring incomplete, errors occurred!
[0.400s] See also "/home/clue/jointer_ws/build/pi_pca9685_interfaces/CMakeFiles/CMakeOutput.log".
[0.403s] Invoked command in '/home/clue/jointer_ws/build/pi_pca9685_interfaces' returned '1': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake /home/clue/jointer_ws/src/pi_pca9685_interfaces -DCMAKE_INSTALL_PREFIX=/home/clue/jointer_ws/install/pi_pca9685_interfaces
